### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by EmilioCenturion** [ahalaburda/jaguaos#1]
add     Suma dos registradores, almazenando el resultado en el destino

```
    add RA, RB  - Suma RA+RB y pone el resultado en RA
```

**Comment by willymarpuk** [comment]
Se agrego la funcion add, para el mismo se agrego el archivo A4.sh, la suma se realiza con numeros decimales previamente cargados en los registros a utilizar.

**Comment by willymarpuk** [comment]
Falta actualizar los flags y el acumulador

**Comment by willymarpuk** [comment]
Falta hacer calculo con valores hexadecimales

**Comment by willymarpuk** [comment]
Ya se actualizan los flags y el acumulador, tambien ya se realizan los calculos en hexadecimal.

Al guardar el resultado hexadecimal en el acumulador me lanza el sgte. error "/opt/jaguaOs/config/ASMFunctions.sh: line 141: [: 2A: integer expression expected"

**Comment by willymarpuk** [comment]
Para solucionar este problema se opto por guardar directamente al acumulador en decimal y en los registros en hexadecimal.
